services:
  - type: web
    name: oktaflix-configurado
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    region: oregon
    healthCheckPath: /
    ports:
      - 8096
